#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : xclip
Version  : 0.13
Release  : 9
URL      : https://github.com/astrand/xclip/archive/0.13.tar.gz
Source0  : https://github.com/astrand/xclip/archive/0.13.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : GPL-2.0 GPL-2.0+
Requires: xclip-bin = %{version}-%{release}
Requires: xclip-license = %{version}-%{release}
Requires: xclip-man = %{version}-%{release}
BuildRequires : pkgconfig(x11)
BuildRequires : pkgconfig(xmu)

%description
xclip is a command line utility that is designed to run on any system with an
X11 implementation. It provides an interface to X selections ("the clipboard")
from the command line. It can read data from standard in or a file and place it
in an X selection for pasting into other X applications. xclip can also print
an X selection to standard out, which can then be redirected to a file or
another program.

%package bin
Summary: bin components for the xclip package.
Group: Binaries
Requires: xclip-license = %{version}-%{release}

%description bin
bin components for the xclip package.


%package license
Summary: license components for the xclip package.
Group: Default

%description license
license components for the xclip package.


%package man
Summary: man components for the xclip package.
Group: Default

%description man
man components for the xclip package.


%prep
%setup -q -n xclip-0.13
cd %{_builddir}/xclip-0.13

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1604356810
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FCFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=4 "
export FFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=4 "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=4 "
%reconfigure --disable-static
make  %{?_smp_mflags}

%install
export SOURCE_DATE_EPOCH=1604356810
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/xclip
cp %{_builddir}/xclip-0.13/COPYING %{buildroot}/usr/share/package-licenses/xclip/0b184ad51ba2a79e85d2288d5fcf8a1ea0481ea4
%make_install

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/xclip
/usr/bin/xclip-copyfile
/usr/bin/xclip-cutfile
/usr/bin/xclip-pastefile

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/xclip/0b184ad51ba2a79e85d2288d5fcf8a1ea0481ea4

%files man
%defattr(0644,root,root,0755)
/usr/share/man/man1/xclip-copyfile.1
/usr/share/man/man1/xclip.1
